// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detect.proto

#include "detect.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_detect_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_detect_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BoxRect;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_detect_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_CameraRect;
}  // namespace protobuf_detect_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace Detect {
class BoxRectDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BoxRect>
      _instance;
} _BoxRect_default_instance_;
class CameraRectDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CameraRect>
      _instance;
} _CameraRect_default_instance_;
class DetectRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DetectRequest>
      _instance;
} _DetectRequest_default_instance_;
class DetectResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DetectResponse>
      _instance;
} _DetectResponse_default_instance_;
}  // namespace Detect
namespace protobuf_detect_2eproto {
static void InitDefaultsBoxRect() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Detect::_BoxRect_default_instance_;
    new (ptr) ::Detect::BoxRect();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Detect::BoxRect::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BoxRect =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBoxRect}, {}};

static void InitDefaultsCameraRect() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Detect::_CameraRect_default_instance_;
    new (ptr) ::Detect::CameraRect();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Detect::CameraRect::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CameraRect =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCameraRect}, {
      &protobuf_detect_2eproto::scc_info_BoxRect.base,}};

static void InitDefaultsDetectRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Detect::_DetectRequest_default_instance_;
    new (ptr) ::Detect::DetectRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Detect::DetectRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DetectRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDetectRequest}, {}};

static void InitDefaultsDetectResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Detect::_DetectResponse_default_instance_;
    new (ptr) ::Detect::DetectResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Detect::DetectResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_DetectResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsDetectResponse}, {
      &protobuf_detect_2eproto::scc_info_CameraRect.base,
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BoxRect.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CameraRect.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DetectRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DetectResponse.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::BoxRect, class_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::CameraRect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::CameraRect, camera_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::CameraRect, box_rect_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectRequest, status_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectResponse, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectResponse, camera_rect_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Detect::DetectResponse, resp_timestamp_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Detect::BoxRect)},
  { 10, -1, sizeof(::Detect::CameraRect)},
  { 17, -1, sizeof(::Detect::DetectRequest)},
  { 23, -1, sizeof(::Detect::DetectResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Detect::_BoxRect_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Detect::_CameraRect_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Detect::_DetectRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Detect::_DetectResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "detect.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014detect.proto\022\006Detect\032\037google/protobuf/"
      "timestamp.proto\"P\n\007BoxRect\022\t\n\001x\030\001 \001(\001\022\t\n"
      "\001y\030\002 \001(\001\022\r\n\005width\030\003 \001(\001\022\016\n\006height\030\004 \001(\001\022"
      "\020\n\010class_id\030\005 \001(\003\"B\n\nCameraRect\022\021\n\tcamer"
      "a_id\030\001 \001(\003\022!\n\010box_rect\030\002 \003(\0132\017.Detect.Bo"
      "xRect\"\037\n\rDetectRequest\022\016\n\006status\030\001 \001(\010\"}"
      "\n\016DetectResponse\022\016\n\006status\030\001 \001(\010\022\'\n\013came"
      "ra_rect\030\002 \003(\0132\022.Detect.CameraRect\0222\n\016res"
      "p_timestamp\030\003 \001(\0132\032.google.protobuf.Time"
      "stamp2V\n\023DetectResultService\022\?\n\014Detected"
      "Rect\022\025.Detect.DetectRequest\032\026.Detect.Det"
      "ectResponse\"\000B\030Z\026/detect_service;Detectb"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 487);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "detect.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_detect_2eproto
namespace Detect {

// ===================================================================

void BoxRect::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BoxRect::kXFieldNumber;
const int BoxRect::kYFieldNumber;
const int BoxRect::kWidthFieldNumber;
const int BoxRect::kHeightFieldNumber;
const int BoxRect::kClassIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BoxRect::BoxRect()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detect_2eproto::scc_info_BoxRect.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detect.BoxRect)
}
BoxRect::BoxRect(const BoxRect& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&class_id_) -
    reinterpret_cast<char*>(&x_)) + sizeof(class_id_));
  // @@protoc_insertion_point(copy_constructor:Detect.BoxRect)
}

void BoxRect::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&class_id_) -
      reinterpret_cast<char*>(&x_)) + sizeof(class_id_));
}

BoxRect::~BoxRect() {
  // @@protoc_insertion_point(destructor:Detect.BoxRect)
  SharedDtor();
}

void BoxRect::SharedDtor() {
}

void BoxRect::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BoxRect::descriptor() {
  ::protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BoxRect& BoxRect::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detect_2eproto::scc_info_BoxRect.base);
  return *internal_default_instance();
}


void BoxRect::Clear() {
// @@protoc_insertion_point(message_clear_start:Detect.BoxRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&class_id_) -
      reinterpret_cast<char*>(&x_)) + sizeof(class_id_));
  _internal_metadata_.Clear();
}

bool BoxRect::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detect.BoxRect)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double width = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double height = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 class_id = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &class_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detect.BoxRect)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detect.BoxRect)
  return false;
#undef DO_
}

void BoxRect::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detect.BoxRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // double width = 3;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->width(), output);
  }

  // double height = 4;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->height(), output);
  }

  // int64 class_id = 5;
  if (this->class_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->class_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Detect.BoxRect)
}

::google::protobuf::uint8* BoxRect::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Detect.BoxRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // double width = 3;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->width(), target);
  }

  // double height = 4;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->height(), target);
  }

  // int64 class_id = 5;
  if (this->class_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->class_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Detect.BoxRect)
  return target;
}

size_t BoxRect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detect.BoxRect)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // double width = 3;
  if (this->width() != 0) {
    total_size += 1 + 8;
  }

  // double height = 4;
  if (this->height() != 0) {
    total_size += 1 + 8;
  }

  // int64 class_id = 5;
  if (this->class_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->class_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BoxRect::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detect.BoxRect)
  GOOGLE_DCHECK_NE(&from, this);
  const BoxRect* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BoxRect>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detect.BoxRect)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detect.BoxRect)
    MergeFrom(*source);
  }
}

void BoxRect::MergeFrom(const BoxRect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detect.BoxRect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.class_id() != 0) {
    set_class_id(from.class_id());
  }
}

void BoxRect::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detect.BoxRect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoxRect::CopyFrom(const BoxRect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detect.BoxRect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxRect::IsInitialized() const {
  return true;
}

void BoxRect::Swap(BoxRect* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BoxRect::InternalSwap(BoxRect* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(class_id_, other->class_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BoxRect::GetMetadata() const {
  protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CameraRect::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraRect::kCameraIdFieldNumber;
const int CameraRect::kBoxRectFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraRect::CameraRect()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detect_2eproto::scc_info_CameraRect.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detect.CameraRect)
}
CameraRect::CameraRect(const CameraRect& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      box_rect_(from.box_rect_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  camera_id_ = from.camera_id_;
  // @@protoc_insertion_point(copy_constructor:Detect.CameraRect)
}

void CameraRect::SharedCtor() {
  camera_id_ = GOOGLE_LONGLONG(0);
}

CameraRect::~CameraRect() {
  // @@protoc_insertion_point(destructor:Detect.CameraRect)
  SharedDtor();
}

void CameraRect::SharedDtor() {
}

void CameraRect::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CameraRect::descriptor() {
  ::protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CameraRect& CameraRect::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detect_2eproto::scc_info_CameraRect.base);
  return *internal_default_instance();
}


void CameraRect::Clear() {
// @@protoc_insertion_point(message_clear_start:Detect.CameraRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  box_rect_.Clear();
  camera_id_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool CameraRect::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detect.CameraRect)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 camera_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &camera_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .Detect.BoxRect box_rect = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_box_rect()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detect.CameraRect)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detect.CameraRect)
  return false;
#undef DO_
}

void CameraRect::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detect.CameraRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 camera_id = 1;
  if (this->camera_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->camera_id(), output);
  }

  // repeated .Detect.BoxRect box_rect = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->box_rect_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->box_rect(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Detect.CameraRect)
}

::google::protobuf::uint8* CameraRect::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Detect.CameraRect)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 camera_id = 1;
  if (this->camera_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->camera_id(), target);
  }

  // repeated .Detect.BoxRect box_rect = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->box_rect_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->box_rect(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Detect.CameraRect)
  return target;
}

size_t CameraRect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detect.CameraRect)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Detect.BoxRect box_rect = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->box_rect_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->box_rect(static_cast<int>(i)));
    }
  }

  // int64 camera_id = 1;
  if (this->camera_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->camera_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CameraRect::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detect.CameraRect)
  GOOGLE_DCHECK_NE(&from, this);
  const CameraRect* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraRect>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detect.CameraRect)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detect.CameraRect)
    MergeFrom(*source);
  }
}

void CameraRect::MergeFrom(const CameraRect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detect.CameraRect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  box_rect_.MergeFrom(from.box_rect_);
  if (from.camera_id() != 0) {
    set_camera_id(from.camera_id());
  }
}

void CameraRect::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detect.CameraRect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraRect::CopyFrom(const CameraRect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detect.CameraRect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraRect::IsInitialized() const {
  return true;
}

void CameraRect::Swap(CameraRect* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraRect::InternalSwap(CameraRect* other) {
  using std::swap;
  CastToBase(&box_rect_)->InternalSwap(CastToBase(&other->box_rect_));
  swap(camera_id_, other->camera_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CameraRect::GetMetadata() const {
  protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DetectRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DetectRequest::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DetectRequest::DetectRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detect_2eproto::scc_info_DetectRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detect.DetectRequest)
}
DetectRequest::DetectRequest(const DetectRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:Detect.DetectRequest)
}

void DetectRequest::SharedCtor() {
  status_ = false;
}

DetectRequest::~DetectRequest() {
  // @@protoc_insertion_point(destructor:Detect.DetectRequest)
  SharedDtor();
}

void DetectRequest::SharedDtor() {
}

void DetectRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DetectRequest::descriptor() {
  ::protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DetectRequest& DetectRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detect_2eproto::scc_info_DetectRequest.base);
  return *internal_default_instance();
}


void DetectRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Detect.DetectRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_ = false;
  _internal_metadata_.Clear();
}

bool DetectRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detect.DetectRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detect.DetectRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detect.DetectRequest)
  return false;
#undef DO_
}

void DetectRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detect.DetectRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Detect.DetectRequest)
}

::google::protobuf::uint8* DetectRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Detect.DetectRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Detect.DetectRequest)
  return target;
}

size_t DetectRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detect.DetectRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DetectRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detect.DetectRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DetectRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detect.DetectRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detect.DetectRequest)
    MergeFrom(*source);
  }
}

void DetectRequest::MergeFrom(const DetectRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detect.DetectRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    set_status(from.status());
  }
}

void DetectRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detect.DetectRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectRequest::CopyFrom(const DetectRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detect.DetectRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectRequest::IsInitialized() const {
  return true;
}

void DetectRequest::Swap(DetectRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DetectRequest::InternalSwap(DetectRequest* other) {
  using std::swap;
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DetectRequest::GetMetadata() const {
  protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DetectResponse::InitAsDefaultInstance() {
  ::Detect::_DetectResponse_default_instance_._instance.get_mutable()->resp_timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
}
void DetectResponse::clear_resp_timestamp() {
  if (GetArenaNoVirtual() == NULL && resp_timestamp_ != NULL) {
    delete resp_timestamp_;
  }
  resp_timestamp_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DetectResponse::kStatusFieldNumber;
const int DetectResponse::kCameraRectFieldNumber;
const int DetectResponse::kRespTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DetectResponse::DetectResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detect_2eproto::scc_info_DetectResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detect.DetectResponse)
}
DetectResponse::DetectResponse(const DetectResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      camera_rect_(from.camera_rect_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_resp_timestamp()) {
    resp_timestamp_ = new ::google::protobuf::Timestamp(*from.resp_timestamp_);
  } else {
    resp_timestamp_ = NULL;
  }
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:Detect.DetectResponse)
}

void DetectResponse::SharedCtor() {
  ::memset(&resp_timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&resp_timestamp_)) + sizeof(status_));
}

DetectResponse::~DetectResponse() {
  // @@protoc_insertion_point(destructor:Detect.DetectResponse)
  SharedDtor();
}

void DetectResponse::SharedDtor() {
  if (this != internal_default_instance()) delete resp_timestamp_;
}

void DetectResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DetectResponse::descriptor() {
  ::protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DetectResponse& DetectResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detect_2eproto::scc_info_DetectResponse.base);
  return *internal_default_instance();
}


void DetectResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Detect.DetectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  camera_rect_.Clear();
  if (GetArenaNoVirtual() == NULL && resp_timestamp_ != NULL) {
    delete resp_timestamp_;
  }
  resp_timestamp_ = NULL;
  status_ = false;
  _internal_metadata_.Clear();
}

bool DetectResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detect.DetectResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .Detect.CameraRect camera_rect = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_camera_rect()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp resp_timestamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_resp_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detect.DetectResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detect.DetectResponse)
  return false;
#undef DO_
}

void DetectResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detect.DetectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  // repeated .Detect.CameraRect camera_rect = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->camera_rect_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->camera_rect(static_cast<int>(i)),
      output);
  }

  // .google.protobuf.Timestamp resp_timestamp = 3;
  if (this->has_resp_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_resp_timestamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Detect.DetectResponse)
}

::google::protobuf::uint8* DetectResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Detect.DetectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  // repeated .Detect.CameraRect camera_rect = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->camera_rect_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->camera_rect(static_cast<int>(i)), deterministic, target);
  }

  // .google.protobuf.Timestamp resp_timestamp = 3;
  if (this->has_resp_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_resp_timestamp(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Detect.DetectResponse)
  return target;
}

size_t DetectResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detect.DetectResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Detect.CameraRect camera_rect = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->camera_rect_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->camera_rect(static_cast<int>(i)));
    }
  }

  // .google.protobuf.Timestamp resp_timestamp = 3;
  if (this->has_resp_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *resp_timestamp_);
  }

  // bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DetectResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detect.DetectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DetectResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detect.DetectResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detect.DetectResponse)
    MergeFrom(*source);
  }
}

void DetectResponse::MergeFrom(const DetectResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detect.DetectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  camera_rect_.MergeFrom(from.camera_rect_);
  if (from.has_resp_timestamp()) {
    mutable_resp_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.resp_timestamp());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void DetectResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detect.DetectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectResponse::CopyFrom(const DetectResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detect.DetectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectResponse::IsInitialized() const {
  return true;
}

void DetectResponse::Swap(DetectResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DetectResponse::InternalSwap(DetectResponse* other) {
  using std::swap;
  CastToBase(&camera_rect_)->InternalSwap(CastToBase(&other->camera_rect_));
  swap(resp_timestamp_, other->resp_timestamp_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DetectResponse::GetMetadata() const {
  protobuf_detect_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detect_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Detect
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Detect::BoxRect* Arena::CreateMaybeMessage< ::Detect::BoxRect >(Arena* arena) {
  return Arena::CreateInternal< ::Detect::BoxRect >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Detect::CameraRect* Arena::CreateMaybeMessage< ::Detect::CameraRect >(Arena* arena) {
  return Arena::CreateInternal< ::Detect::CameraRect >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Detect::DetectRequest* Arena::CreateMaybeMessage< ::Detect::DetectRequest >(Arena* arena) {
  return Arena::CreateInternal< ::Detect::DetectRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Detect::DetectResponse* Arena::CreateMaybeMessage< ::Detect::DetectResponse >(Arena* arena) {
  return Arena::CreateInternal< ::Detect::DetectResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
