// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detect.proto

#ifndef PROTOBUF_INCLUDED_detect_2eproto
#define PROTOBUF_INCLUDED_detect_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_detect_2eproto 

namespace protobuf_detect_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_detect_2eproto
namespace Detect {
class BoxRect;
class BoxRectDefaultTypeInternal;
extern BoxRectDefaultTypeInternal _BoxRect_default_instance_;
class DetectRequest;
class DetectRequestDefaultTypeInternal;
extern DetectRequestDefaultTypeInternal _DetectRequest_default_instance_;
class DetectResponse;
class DetectResponseDefaultTypeInternal;
extern DetectResponseDefaultTypeInternal _DetectResponse_default_instance_;
}  // namespace Detect
namespace google {
namespace protobuf {
template<> ::Detect::BoxRect* Arena::CreateMaybeMessage<::Detect::BoxRect>(Arena*);
template<> ::Detect::DetectRequest* Arena::CreateMaybeMessage<::Detect::DetectRequest>(Arena*);
template<> ::Detect::DetectResponse* Arena::CreateMaybeMessage<::Detect::DetectResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Detect {

// ===================================================================

class BoxRect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Detect.BoxRect) */ {
 public:
  BoxRect();
  virtual ~BoxRect();

  BoxRect(const BoxRect& from);

  inline BoxRect& operator=(const BoxRect& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BoxRect(BoxRect&& from) noexcept
    : BoxRect() {
    *this = ::std::move(from);
  }

  inline BoxRect& operator=(BoxRect&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BoxRect& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BoxRect* internal_default_instance() {
    return reinterpret_cast<const BoxRect*>(
               &_BoxRect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BoxRect* other);
  friend void swap(BoxRect& a, BoxRect& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BoxRect* New() const final {
    return CreateMaybeMessage<BoxRect>(NULL);
  }

  BoxRect* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BoxRect>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BoxRect& from);
  void MergeFrom(const BoxRect& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BoxRect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // double width = 3;
  void clear_width();
  static const int kWidthFieldNumber = 3;
  double width() const;
  void set_width(double value);

  // double height = 4;
  void clear_height();
  static const int kHeightFieldNumber = 4;
  double height() const;
  void set_height(double value);

  // int64 class_id = 5;
  void clear_class_id();
  static const int kClassIdFieldNumber = 5;
  ::google::protobuf::int64 class_id() const;
  void set_class_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Detect.BoxRect)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double width_;
  double height_;
  ::google::protobuf::int64 class_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_detect_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DetectRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Detect.DetectRequest) */ {
 public:
  DetectRequest();
  virtual ~DetectRequest();

  DetectRequest(const DetectRequest& from);

  inline DetectRequest& operator=(const DetectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetectRequest(DetectRequest&& from) noexcept
    : DetectRequest() {
    *this = ::std::move(from);
  }

  inline DetectRequest& operator=(DetectRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DetectRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectRequest* internal_default_instance() {
    return reinterpret_cast<const DetectRequest*>(
               &_DetectRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DetectRequest* other);
  friend void swap(DetectRequest& a, DetectRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetectRequest* New() const final {
    return CreateMaybeMessage<DetectRequest>(NULL);
  }

  DetectRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetectRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetectRequest& from);
  void MergeFrom(const DetectRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetectRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  bool status() const;
  void set_status(bool value);

  // @@protoc_insertion_point(class_scope:Detect.DetectRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_detect_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DetectResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Detect.DetectResponse) */ {
 public:
  DetectResponse();
  virtual ~DetectResponse();

  DetectResponse(const DetectResponse& from);

  inline DetectResponse& operator=(const DetectResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetectResponse(DetectResponse&& from) noexcept
    : DetectResponse() {
    *this = ::std::move(from);
  }

  inline DetectResponse& operator=(DetectResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DetectResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectResponse* internal_default_instance() {
    return reinterpret_cast<const DetectResponse*>(
               &_DetectResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DetectResponse* other);
  friend void swap(DetectResponse& a, DetectResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetectResponse* New() const final {
    return CreateMaybeMessage<DetectResponse>(NULL);
  }

  DetectResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetectResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetectResponse& from);
  void MergeFrom(const DetectResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetectResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Detect.BoxRect rect = 2;
  int rect_size() const;
  void clear_rect();
  static const int kRectFieldNumber = 2;
  ::Detect::BoxRect* mutable_rect(int index);
  ::google::protobuf::RepeatedPtrField< ::Detect::BoxRect >*
      mutable_rect();
  const ::Detect::BoxRect& rect(int index) const;
  ::Detect::BoxRect* add_rect();
  const ::google::protobuf::RepeatedPtrField< ::Detect::BoxRect >&
      rect() const;

  // bool status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  bool status() const;
  void set_status(bool value);

  // @@protoc_insertion_point(class_scope:Detect.DetectResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Detect::BoxRect > rect_;
  bool status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_detect_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BoxRect

// double x = 1;
inline void BoxRect::clear_x() {
  x_ = 0;
}
inline double BoxRect::x() const {
  // @@protoc_insertion_point(field_get:Detect.BoxRect.x)
  return x_;
}
inline void BoxRect::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Detect.BoxRect.x)
}

// double y = 2;
inline void BoxRect::clear_y() {
  y_ = 0;
}
inline double BoxRect::y() const {
  // @@protoc_insertion_point(field_get:Detect.BoxRect.y)
  return y_;
}
inline void BoxRect::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Detect.BoxRect.y)
}

// double width = 3;
inline void BoxRect::clear_width() {
  width_ = 0;
}
inline double BoxRect::width() const {
  // @@protoc_insertion_point(field_get:Detect.BoxRect.width)
  return width_;
}
inline void BoxRect::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:Detect.BoxRect.width)
}

// double height = 4;
inline void BoxRect::clear_height() {
  height_ = 0;
}
inline double BoxRect::height() const {
  // @@protoc_insertion_point(field_get:Detect.BoxRect.height)
  return height_;
}
inline void BoxRect::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Detect.BoxRect.height)
}

// int64 class_id = 5;
inline void BoxRect::clear_class_id() {
  class_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 BoxRect::class_id() const {
  // @@protoc_insertion_point(field_get:Detect.BoxRect.class_id)
  return class_id_;
}
inline void BoxRect::set_class_id(::google::protobuf::int64 value) {
  
  class_id_ = value;
  // @@protoc_insertion_point(field_set:Detect.BoxRect.class_id)
}

// -------------------------------------------------------------------

// DetectRequest

// bool status = 1;
inline void DetectRequest::clear_status() {
  status_ = false;
}
inline bool DetectRequest::status() const {
  // @@protoc_insertion_point(field_get:Detect.DetectRequest.status)
  return status_;
}
inline void DetectRequest::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:Detect.DetectRequest.status)
}

// -------------------------------------------------------------------

// DetectResponse

// bool status = 1;
inline void DetectResponse::clear_status() {
  status_ = false;
}
inline bool DetectResponse::status() const {
  // @@protoc_insertion_point(field_get:Detect.DetectResponse.status)
  return status_;
}
inline void DetectResponse::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:Detect.DetectResponse.status)
}

// repeated .Detect.BoxRect rect = 2;
inline int DetectResponse::rect_size() const {
  return rect_.size();
}
inline void DetectResponse::clear_rect() {
  rect_.Clear();
}
inline ::Detect::BoxRect* DetectResponse::mutable_rect(int index) {
  // @@protoc_insertion_point(field_mutable:Detect.DetectResponse.rect)
  return rect_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Detect::BoxRect >*
DetectResponse::mutable_rect() {
  // @@protoc_insertion_point(field_mutable_list:Detect.DetectResponse.rect)
  return &rect_;
}
inline const ::Detect::BoxRect& DetectResponse::rect(int index) const {
  // @@protoc_insertion_point(field_get:Detect.DetectResponse.rect)
  return rect_.Get(index);
}
inline ::Detect::BoxRect* DetectResponse::add_rect() {
  // @@protoc_insertion_point(field_add:Detect.DetectResponse.rect)
  return rect_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Detect::BoxRect >&
DetectResponse::rect() const {
  // @@protoc_insertion_point(field_list:Detect.DetectResponse.rect)
  return rect_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Detect

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_detect_2eproto
